/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectselma;

import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Manuel
 */
public class Pral extends javax.swing.JFrame {

    /**
     * Creates new form Pral
     */
    public Pral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtC1 = new javax.swing.JTextField();
        txtC2 = new javax.swing.JTextField();
        lblC1 = new javax.swing.JLabel();
        txtHipo = new javax.swing.JTextField();
        lblC2 = new javax.swing.JLabel();
        lblHipo = new javax.swing.JLabel();
        btnCalcularHipo = new javax.swing.JButton();
        btnCalcularC2 = new javax.swing.JButton();
        btnCalcularC1 = new javax.swing.JButton();
        btnLimpia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cateto 1");

        jLabel2.setText("Cateto 2");

        jLabel3.setText("Hipotenusa");

        txtC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtC1ActionPerformed(evt);
            }
        });

        txtC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtC2ActionPerformed(evt);
            }
        });

        lblC1.setText("Resultado");

        txtHipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHipoActionPerformed(evt);
            }
        });

        lblC2.setText("Resultado");

        lblHipo.setText("Resultado");

        btnCalcularHipo.setText("Calcular Hipotenusa");
        btnCalcularHipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularHipoActionPerformed(evt);
            }
        });

        btnCalcularC2.setText("Calcular C2");
        btnCalcularC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularC2ActionPerformed(evt);
            }
        });

        btnCalcularC1.setText("Calcular C1");
        btnCalcularC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularC1ActionPerformed(evt);
            }
        });

        btnLimpia.setText("Limpiar");
        btnLimpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHipo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtC1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtC2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblC1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalcularC1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblC2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalcularC2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblHipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalcularHipo)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(btnLimpia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblC1)
                    .addComponent(btnCalcularC1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblC2)
                    .addComponent(btnCalcularC2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHipo)
                    .addComponent(btnCalcularHipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnLimpia)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Double c1, c2, hipo;
    private void btnCalcularHipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularHipoActionPerformed
        c1 = Double.parseDouble(txtC1.getText());
        c2 = Double.parseDouble(txtC2.getText());
        
        hipo = calculaHipotenusa(c1, c2);
     
        lblHipo.setText(hipo.toString());  
    }//GEN-LAST:event_btnCalcularHipoActionPerformed

    private void txtC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtC1ActionPerformed
        c1 = Double.parseDouble(txtC1.getText());
    }//GEN-LAST:event_txtC1ActionPerformed

    private void txtC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtC2ActionPerformed
        c2 = Double.parseDouble(txtC2.getText());
    }//GEN-LAST:event_txtC2ActionPerformed

    private void txtHipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHipoActionPerformed
        hipo = Double.parseDouble(txtHipo.getText());
    }//GEN-LAST:event_txtHipoActionPerformed

    private void btnCalcularC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularC2ActionPerformed
        c1 = Double.parseDouble(txtC1.getText());
        hipo = Double.parseDouble(txtHipo.getText());
        
        c2 = calculaC1(c1, hipo);
        
        lblC2.setText(c2.toString());
    }//GEN-LAST:event_btnCalcularC2ActionPerformed

    private void btnCalcularC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularC1ActionPerformed
        hipo = Double.parseDouble(txtHipo.getText());
        c2 = Double.parseDouble(txtC2.getText());
        
        c1 = calculaC1(c2, hipo);
        
        lblC1.setText(c1.toString());
    }//GEN-LAST:event_btnCalcularC1ActionPerformed

    private void btnLimpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiaActionPerformed
        txtC1.setText("");
        txtC2.setText("");
        txtHipo.setText("");
        lblC1.setText("Resultado");
        lblC2.setText("Resultado");
        lblHipo.setText("Resultado");
    }//GEN-LAST:event_btnLimpiaActionPerformed
    
    private Double calculaHipotenusa(Double c1,Double c2){
        Double hipo = Math.sqrt(Math.pow(c1, 2)+ Math.pow(c2, 2));           
        return hipo;
    }
    
    private Double calculaC1(Double c2, Double hipo){
        Double c1= Math.sqrt(Math.pow(hipo, 2)-Math.pow(c2, 2));
        return c1;
    }
    
    private Double calculaC2(Double cat1, Double hipo){
        Double cat2= Math.sqrt(Math.pow(hipo, 2)-Math.pow(c1, 2));
        return cat2;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularC1;
    private javax.swing.JButton btnCalcularC2;
    private javax.swing.JButton btnCalcularHipo;
    private javax.swing.JButton btnLimpia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblC1;
    private javax.swing.JLabel lblC2;
    private javax.swing.JLabel lblHipo;
    private javax.swing.JTextField txtC1;
    private javax.swing.JTextField txtC2;
    private javax.swing.JTextField txtHipo;
    // End of variables declaration//GEN-END:variables
}
